# WARNING - Generated by {fusen} from dev/get_data.Rmd: do not edit by hand


#' 1171 entries commune level housing data for Luxemborg
#' \itemize{
#' \item year. year of listing
#' \item locality. local authority (smallest administrative divisions of territory)
#' \item n_offers. total number of selling offers
#' \item average_price_nominal_euros. average selling price in nominal euros
#' \item average_price_m2_nominal_euros. average selling price in square meters in nominal euros
#' }
#' @docType data
#' @keywords datasets
#' @name commune_level_data
#' @usage data(commune_level_data)
#' @format A data frame with 1171 rows and 5 columns
NULL

data("commune_level_data", envir = environment())


#' 11 entries country level housing data for Luxemborg
#' \itemize{
#' \item year. year of listing
#' \item locality. local authority (smallest administrative divisions of territory)
#' \item n_offers. total number of selling offers
#' \item average_price_nominal_euros. average selling price in nominal euros
#' \item average_price_m2_nominal_euros. average selling price in square meters in nominal euros
#' }
#' @docType data
#' @keywords datasets
#' @name commune_level_data
#' @usage data(commune_level_data)
#' @format A data frame with 11 rows and 5 columns
NULL

data("country_level_data", envir = environment())
