# WARNING - Generated by {fusen} from dev/analyze.Rmd: do not edit by hand

#' Draw some plots
#'
#' @param dataset The dataset for which the index needs to be computed
#' @importFrom dplyr group_by ungroup mutate
#' @importFrom rlang quo
#' @importFrom tidyr fill
#' @return The input dataset with added columns: p0, p0_m2, pl and pl_m2. p0 are prices at year 0 (2010), and pl are the index.
#' @export
#' @examples
#' \dontrun{ 
#' commune_level_data <- get_laspeyeres(commune_level_data)
#' country_level_data <- get_laspeyeres(country_level_data)
#' }
get_laspeyeres <- function(dataset){

  which_dataset <- deparse(substitute(dataset))

  group_var <- if(grepl("commune", which_dataset)){
                 quo(locality)
               } else {
                 NULL
               }
  dataset |>
    group_by(!!group_var) |>
    mutate(p0 = ifelse(year == "2010", average_price_nominal_euros, NA)) |>
    fill(p0, .direction = "down") |>
    mutate(p0_m2 = ifelse(year == "2010", average_price_m2_nominal_euros, NA)) |>
    fill(p0_m2, .direction = "down") |>
    ungroup() |>
    mutate(pl = average_price_nominal_euros/p0*100,
           pl_m2 = average_price_m2_nominal_euros/p0_m2*100)

}

# communes <- c("Luxembourg",
#               "Esch-sur-Alzette",
#               "Mamer",
#               "Schengen",
#               "Wincrange")

# make a plotting function

#' Plot price index
#'
#' @param country_level_data The country level data frame
#' @param commune_level_data The commune level data frame
#' @param commune The commune to plot
#' @importFrom dplyr filter bind_rows
#' @importFrom here here
#' @importFrom ggplot2 ggplot geom_line aes ggsave scale_x_date
#' @return A ggplot
#' @export
#'
#' @examples
#' \dontrun{
#'commune_level_data_laspeyeres <- get_laspeyeres(commune_level_data)
#'make_plot(commune_level_data_laspeyeres, "Luxembourg")
#' }
#'

make_plot <- function(country_level_data,
                      commune_level_data,
                      commune){
  
  filtered_data <- commune_level_data |>
    filter(locality == commune)
  
  data_to_plot <- bind_rows(
    country_level_data,
    filtered_data
  ) |> mutate(
    year = as.Date(as.character(year), format = "%Y")
  )
  
  p <- ggplot(data_to_plot) +
    geom_line(aes(y = pl_m2,
                  x = year,
                  group = locality,
                  colour = locality)) + scale_x_date()
 ggsave(file.path(here(), "plots", paste0(commune, "_plot", ".pdf")), p)
}
